"""Initial schema: Users, Logs, Meals, Ingredients

Revision ID: e2ed49bf4b7a
Revises: 
Create Date: 2026-03-20 10:16:05.802654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ed49bf4b7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_calories', sa.Integer(), nullable=False),
    sa.Column('total_protein', sa.Integer(), nullable=False),
    sa.Column('total_carbs', sa.Integer(), nullable=False),
    sa.Column('total_fat', sa.Integer(), nullable=False),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_logs'))
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.Column('carbs', sa.Integer(), nullable=False),
    sa.Column('fat', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ingredients_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    op.create_table('meal_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_meal_ingredients_ingredient_id_ingredients')),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_ingredients_meal_id_meals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_ingredients'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_ingredients')
    op.drop_table('meals')
    op.drop_table('ingredients')
    op.drop_table('daily_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
